### ISSUE TITLE
Upgranding to angular 9/Ivy compiler

### ISSUE THREAD

**Issue by st-clair-clarke** [ng-turkey/ngx-context#12] opened 2020-01-21 19:09 UTC
**Is your feature request related to a problem? Please describe.**
Yes. The current version does NOT supports Ivy/angular 9

**Describe the solution you'd like**
Support for  angular 9
Angular 9 release is pending. I am using the current release candidate, but your package does not support angular 9/Ivy.

Please consider upgrading to angular9/Ivy

Cheers

**Comment by mehmet-erim** [comment] 2020-01-22 09:16
There is an issue that caused by Ivy: https://github.com/angular/angular/issues/34819

We will work after this issue is resolved.

**Comment by st-clair-clarke** [comment] 2020-01-22 10:40
Thank you.

**Comment by dumptruckman** [comment] 2020-10-06 19:10
Is there any work around for the issue with Ivy? We'd love to use ngx-context but this is holding us back.

**Comment by mehmet-erim** [comment] 2020-11-09 06:14
The [issue](https://github.com/angular/angular/issues/34819) has been resolved by the Angular team. After Angular v11.0.0 is released, we will release a new version that works with ivy.

**Comment by st-clair-clarke** [comment] 2021-09-03 10:22
Hi, we are now at angular 12. You had promise to resolve this issue in Angular v11.0.0. Is there a timeline for the resolution. Still have a need for the package.

**Comment by mehmet-erim** [comment] 2021-09-09 06:38
Hi @st-clair-clarke

Apologize for the delay.
We've started the work. A new version will be released as soon as possible.

Thanks!

**Closed** 2021-11-03 10:52 UTC
Labels: enhancement

**Comment by behoyh** [comment] 2021-11-03 19:22
AWESOME!! Can we update the package now off npm? Great work!

**Comment by mehmet-erim** [comment] 2021-11-04 13:53
Yes, you can install the v2 by running the command below:

```bash
npm install ngx-context@2
```
